version: "3.9"
services:
  janus-gateway:
    image: canyan/janus-gateway:latest
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    restart: always
    ports:
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    volumes:
      - "./janus-configuration/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./janus-configuration/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
      - "./janus-configuration/janus.plugin.echotest.jcfg:/usr/local/etc/janus/janus.plugin.echotest.jcfg"